print("hello-world")
print("your first name")
print("your first name and last name in a single print statement")
print("the numbers 1,2,and3in a single print statement")
print("hello world")
print("apple,banana,cherry")
print("1-2-3")
print("hello world")
print("12")
print("Hello!")
print("\.")
print("I am 20 years old.")
print("The number is 5.")
print("1")
print("2")
print("3")
print("4")
print("5")
